services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n-main
    ports:
      - "5678:5678"
    volumes:
      - ./data/n8n_storage:/home/node/.n8n
      #- ./data/n8n_runners/n8n-task-runners.json:/etc/n8n-task-runners.json
      #- ./data/n8n_etc:/etc
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=Ul1s3s18!
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - NODE_FUNCTION_ALLOW_EXTERNAL=axios,qs,ioc-finder,redis,elasticsearch,quill-delta-to-markdown
      - N8N_LOG_LEVEL=debug
      - TZ=Europe/Madrid
      - GENERIC_TIMEZONE=Europe/Madrid
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - N8N_RUNNERS_AUTH_TOKEN=Headlock7-Sprawl1-Tweed3-Finally2
      - N8N_NATIVE_PYTHON_RUNNER=true
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:12
    volumes:
      - ./data/db_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - POSTGRES_DB=n8n
    restart: unless-stopped
  
  task-runners:
    # image: n8nio/runners:1.111.0
    image: n8nio/runners:custom
    container_name: n8n-runners
    environment:
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n-main:5679
      - N8N_RUNNERS_AUTH_TOKEN=Headlock7-Sprawl1-Tweed3-Finally2
      - N8N_RUNNERS_LAUNCHER_LOG_LEVEL=debug
    volumes:
      - ./data/n8n_task_runner:/home/node/.n8n
      #- ./data/n8n_runners_2/n8n-task-runners.json:/etc/n8n-task-runners.json
    depends_on:
      - n8n
